### ISSUE TITLE
Embedding Dimension Error in Aggregate Step 

### ISSUE THREAD

**Issue by SLKyrim** [ronaldpereira/pick-and-choose-gnn#1]
Wonderful reproduction work! 
But I ran **main.py** directly in PyCharm, and got the error:

> Traceback (most recent call last):
  File "D:/Gitee/repo-pc-gnn/other_implementation/pick-and-choose-gnn-main/pac_gnn/main.py", line 90, in <module>
    main()
  File "D:/Gitee/repo-pc-gnn/other_implementation/pick-and-choose-gnn-main/pac_gnn/main.py", line 86, in main
    print(message_passing.execute())
  File "D:\Gitee\repo-pc-gnn\other_implementation\pick-and-choose-gnn-main\pac_gnn\aggregate.py", line 125, in execute
    self._update_h_v_r_l(v, v_graph, relation, layer)
  File "D:\Gitee\repo-pc-gnn\other_implementation\pick-and-choose-gnn-main\pac_gnn\aggregate.py", line 97, in _update_h_v_r_l
    np.concatenate((self.h_v_r_l[v, relation, layer - 1], mean_agg), axis=1)
ValueError: could not broadcast input array from shape (10,20) into shape (11,10)

**Comment by ronaldpereira** [comment]
Thanks for the report!
Just confirmed this issue and will fix it asap.

**Comment by ronaldpereira** [comment]
Could you provide me the versions of the numpy and pytorch packages you are using?

**Comment by SLKyrim** [comment]
Sorry for the late reply.
The version of numpy is 1.21.0 and pytorch is 1.6.0.

FYI: I also revised the line 43 in **choose.py** to:

`self._train_distance(self.h, torch.LongTensor(y))`

otherwise PyCharm will raise the error below:

> Traceback (most recent call last):
  File "D:/Gitee/repo-pc-gnn/other_implementation/pick-and-choose-gnn-main/pac_gnn/main.py", line 88, in <module>
    main()
  File "D:/Gitee/repo-pc-gnn/other_implementation/pick-and-choose-gnn-main/pac_gnn/main.py", line 64, in main
    neighborhood_sampler = NeighborhoodSampler(G=G, h=features, y=labels, n_relations=1)
  File "D:\Gitee\repo-pc-gnn\other_implementation\pick-and-choose-gnn-main\pac_gnn\choose.py", line 43, in __init__
    self._train_distance(self.h, torch.tensor(y))
  File "D:\Gitee\repo-pc-gnn\other_implementation\pick-and-choose-gnn-main\pac_gnn\choose.py", line 55, in _train_distance
    loss = loss_fn(y_pred, y)
  File "D:\Softwares\Anaconda3\envs\cs224w\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Softwares\Anaconda3\envs\cs224w\lib\site-packages\torch\nn\modules\loss.py", line 948, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "D:\Softwares\Anaconda3\envs\cs224w\lib\site-packages\torch\nn\functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "D:\Softwares\Anaconda3\envs\cs224w\lib\site-packages\torch\nn\functional.py", line 2218, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: expected scalar type Long but found Int
